{
	"version": 1790778249,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/transição-sheet0.png",
		"images/pdtopt-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/pdttitulo-sheet0.png",
		"images/pdvoltar3-sheet0.png",
		"images/chãoprovisorio-sheet0.png",
		"images/pergamminho-sheet0.png",
		"images/pergamminho-sheet1.png",
		"images/pergamminho-sheet2.png",
		"images/pergamminho-sheet3.png",
		"images/pergamminho-sheet4.png",
		"images/fundo-sheet0.png",
		"images/abaco-sheet0.png",
		"images/bolinha-sheet0.png",
		"images/bolinha2-sheet0.png",
		"images/bolinha2-sheet1.png",
		"images/missão-sheet0.png",
		"images/start-sheet0.png",
		"images/options-sheet0.png",
		"images/exit-sheet0.png",
		"images/voltar-sheet0.png",
		"media/efeito 1.ogg",
		"media/efeito 3.ogg",
		"media/nilo-asministration.ogg",
		"media/scribe_s-quiet-work.ogg",
		"media/hypnotic-egyptian-pulse.ogg",
		"media/modal-reed.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}